Update enforce-required-reviews.yml

diff --git a/.github/workflows/enforce-required-reviews.yml b/.github/workflows/enforce-required-reviews.yml
--- a/.github/workflows/enforce-required-reviews.yml
+++ b/.github/workflows/enforce-required-reviews.yml
@@ -9,53 +9,54 @@ on:
 jobs:
   enforce-reviews:
     runs-on: ubuntu-latest
-
+  
     env:
-      RELEASE_REVIEWER: ThirdFimmiUser  # Define the user as a variable
+      RELEASE_REVIEWER: ThirdFimmiUser  # Define the reviewer
 
     steps:
-      - name: Check if the user is already a reviewer and add if necessary
+      - name: Check if the reviewer is assigned or has left a review
         if: ${{ vars.RELEASE_MODE == 'true' }}
         run: |
           set -x
+          PR_NUMBER="${{ github.event.pull_request.number }}"
+          
           # Get the list of assigned reviewers
           ASSIGNED_REVIEWERS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers)
+            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers)
+          
+          # Get the review statuses for the PR
+          REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews)
 
-          # Check if the user is assigned using if / else 1
-          if "$ASSIGNED_REVIEWERS" | grep -q "$RELEASE_REVIEWERS"; then
-            echo "$RELEASE_REVIEWER is already a reviewer, no need to add."
-          fi
-
-          # Check if the user is assigned using if / else 2
-          if [[ "$ASSIGNED_REVIEWERS" == *"$RELEASE_REVIEWER"* ]]; then
-            echo "$RELEASE_REVIEWER is already a reviewer, no need to add."
+          # Check if the reviewer is assigned or has left any review
+          if echo "$ASSIGNED_REVIEWERS" | grep -q "$RELEASE_REVIEWER"; then
+            echo "$RELEASE_REVIEWER is already assigned as a reviewer."
+          elif echo "$REVIEWS" |  grep -q "$RELEASE_REVIEWER"; then
+            echo "$RELEASE_REVIEWER has already a reviewer."
           else
-            echo "$RELEASE_REVIEWER is not a reviewer yet, adding now."
+            echo "$RELEASE_REVIEWER is neither assigned nor has left a review. Adding as a reviewer now."
 
             # Add the reviewer user using curl
             curl -X POST \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
-              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
+              https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers \
               -d "{\"reviewers\":[\"$RELEASE_REVIEWER\"]}"
 
             # Adding a short delay to ensure the reviewer is registered in the system
             sleep 3
           fi
+      # - name: Check if the reviewer has approved the PR
+      #   if: ${{ vars.RELEASE_MODE == 'true' }}
+      #   run: |
+      #     # Get the review statuses for the PR
+      #     REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+      #       https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)
 
-      - name: Check if the reviewer has approved the PR
-        if: ${{ vars.RELEASE_MODE == 'true' }}
-        run: |
-          # Get the review statuses for the PR
-          REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)
-
-          # Check if the user has approved the PR
-          if [[ "$REVIEWS" == *"$RELEASE_REVIEWER"* && "$REVIEWS" == *"APPROVED"* ]]; then
-            echo "$RELEASE_REVIEWER has approved the PR"
-          else
-            echo "$RELEASE_REVIEWER has not approved the PR"
-            echo "$RELEASE_REVIEWER approval is required since the release is kickstarted"
-            exit 1  # Fail the check if approval is missing
-          fi
+      #     # Check if the RELEASE_REVIEWER has approved the PR
+      #     if echo "$REVIEWS" | jq -e '.[] | select(.user.login == "'"$RELEASE_REVIEWER"'") | select(.state == "APPROVED")' > /dev/null; then
+      #       echo "$RELEASE_REVIEWER has approved the PR"
+      #     else
+      #       echo "$RELEASE_REVIEWER has not approved the PR"
+      #       echo "$RELEASE_REVIEWER approval is required since the release is kickstarted"
+      #       exit 1  # Fail the check if approval is missing
