Update enforce-required-reviews.yml

diff --git a/.github/workflows/enforce-required-reviews.yml b/.github/workflows/enforce-required-reviews.yml
--- a/.github/workflows/enforce-required-reviews.yml
+++ b/.github/workflows/enforce-required-reviews.yml
@@ -12,23 +12,7 @@ jobs:
       RELEASE_REVIEWER: ThirdFimmiUser  # Define the user as a variable
 
     steps:
-      - name: Check release mode and add reviewer if necessary
-        # if: env.RELEASE_MODE == 'true'
-        run: |
-          echo "Release mode is active, assigning $RELEASE_REVIEWER"
-
-          # Add the reviewer user using curl
-          curl -X POST \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
-            -d "{\"reviewers\":[\"$RELEASE_REVIEWER\"]}"
-
-      - name: Wait for 3seconds
-        run: sleep 3
-
-
-      - name: Check if the release-related team has approved the PR
+      - name: Check if the user is already a reviewer and add if necessary
         # if: env.RELEASE_MODE == 'true'
         run: |
           # Get the list of assigned reviewers
@@ -37,19 +21,33 @@ jobs:
 
           # Check if the user is assigned
           if echo "$ASSIGNED_REVIEWERS" | grep -q "$RELEASE_REVIEWER"; then
-            echo "$RELEASE_REVIEWER is assigned"
-
-            # Get the review statuses for the PR
-            REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)
-
-            # Check if the user has approved the PR
-            if echo "$REVIEWS" | grep -q '"state": "APPROVED"' | grep -q "$RELEASE_REVIEWER"; then
-              echo "$RELEASE_REVIEWER has approved the PR"
-            else
-              echo "$RELEASE_REVIEWER has not approved the PR"
-              exit 1  # Fail the check if approval is missing
-            fi
+            echo "$RELEASE_REVIEWER is already a reviewer, no need to add."
           else
-            echo "$RELEASE_REVIEWER is not assigned, skipping check"
-          fi
+            echo "$RELEASE_REVIEWER is not a reviewer yet, adding now."
+
+            # Add the reviewer user using curl
+            curl -X POST \
+              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
+              -d "{\"reviewers\":[\"$RELEASE_REVIEWER\"]}"
+
+            # Adding a short delay to ensure the reviewer is registered in the system
+            sleep 3
+
+      - name: Check if the reviewer has approved the PR
+        # if: env.RELEASE_MODE == 'true'
+        run: |
+          # Get the review statuses for the PR
+          REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)
+
+          echo REVIEWS = $REVIEWS
+
+          # Check if the user has approved the PR
+          if echo "$REVIEWS" | grep -q '"state": "APPROVED"' | grep -q "$RELEASE_REVIEWER"; then
+            echo "$RELEASE_REVIEWER has approved the PR"
+          else
+            echo "$RELEASE_REVIEWER has not approved the PR"
+            echo "$RELEASE_REVIEWER approval is required since the release is kickstarted"
+            exit 1  # Fail the check if approval is missing
